# Glossary {-#glossary} 
<p>**RPA** -- remotely piloted aircraft.
Otherwise known as unmanned aerial vehicles (UAV) or drones.</p>
<p>**RPAS** -- remotely piloted aircraft systems.
RPAS includes RPA as well as software, operating personnel, etc.
Otherwise referred to as unmanned aerial systems (UAS).</p>
<p>**GPS** -- global positioning system.
Most GPS devices communicate with American GPS satellites to determine location information.</p>
<p>**GNSS** -- global navigation satellite system.
GNSS includes all navigation satellite constellations.
Other constellations include the Russian GLONASS (Globalnaya Navigazionnaya Sputnikovaya Sistema), the European Union's Galileo.
GNSS devices can communicate with other satellite constellations in addition to American GPS satellites.</p>
<p>**Pixel** -- Short for pixel element, a pixel is the constituent element of images.
Each pixel of an image contains numerical values known as digital brightness values.
Conventional images contain three channels for red, green, and blue light.
Digital brightness values determine how much red, green, and blue light should be displayed for each pixel.
Digital brightness values typically range from 0-255, with 0 representing no brightness and 255 representing maximum brightness.</p>
<p>**CHM** -- Canopy Height Model.
A two-dimensional digital representation of canopy heights relative to a ground-level.</p>
<p>**DEM** -- Digital Elevation Model.
A two-dimensional digital representation of the surface of the Earth.
DEM are single-channel images.
Lower values correspond to lower elevations and higher values correspond to higher elevations.</p>
<p>**DAP** -- Digital Aerial Photogrammetry.
DAP is the process by which overlapping aerial images are used to derive three-dimensional point cloud data as well as orthorectified imagery products.</p>
<p>**Downwelling light sensor (DLS)** -- An incident light sensor that directly connects to the MicaSense RedEdge camera.
DLS collect information on ambient light during acquisition, which can be used to correct for sudden changes in light that may occur during acquisition.</p>
<p>**GCP** -- Ground Control Point.
GCPs are marked targets that are distributed throughout sites prior to acquisition.
The locations of GCPs are recorded with GNSS devices.
GCPs are located in RPAS imagery during photogrammetric processing and used to improve the geometric accuracy of DAP products.</p>
<p>**Gimbal** -- an instrument which allows a sensor to maintain a constant position while mounted on a moving aircraft.</p>
<p>**GPU** -- Graphics Processing Unit.
GPU are used by computers to display graphics and render video.</p>
<p>**ITC** -- Individual Tree Crown.</p>
<p>**LiDAR** -- Light Detection and Ranging, otherwise known as airborne laser scanning (ALS) -- LiDAR emits light as laser pulses at targets and measures the time it takes for emitted light to return to the sensor.
Each return is recorded as a point in 3-dimensional space.
In the context of forestry, LiDAR is typically collected with piloted aircraft.</p>
<p>**Nadir**- refers to the viewing angle directly below a sensor.</p>
<p>**Orthomosaic** -- an orthorectified image produced by mosaicking images collected by an RPAS.
A primary photogrammetric product.</p>
<p>**PPK** -- Post-Processing Kinematic.
PPK uses satellite carrier data from third-party base stations to apply differential corrections to GNSS data after it has been recorded.</p>
<p>**RTK** -- Real-Time Kinematic.
RTK systems use RPA GNSS to communicate with a transportable base station and differentially correct satellite carrier data in real time.</p>
<p>**SFOC** -- Special Flight Operations Certificate.
An SFOC allows for the operation of RPAS beyond basic or advanced drone pilot certificates.
Pertinent to this report, an SFOC allows for RPAS to be operated beyond visual line of sight and at altitudes greater than 120 metres.
See [here](https://tc.canada.ca/en/aviation/drone-safety/drone-pilot-licensing/get-permission-special-drone-operations) [1] for more.</p>