# Selected Bibliography of Relevant IRSS Publications {#bibliography}
We have included this list of publications – from which the synthesis of this report was largely drawn – in addition to the reference section at the end of this report. 

<ol>
<li>T. R. H. Goodbody, N. C. Coops, P. Tompalski, P. Crawford, and K. J. K. Day, “Updating residual stem volume estimates using ALS- and UAV-acquired stereo-photogrammetric point clouds,” Int. J. Remote Sens., vol. 38, no. 8–10, pp. 2938–2953, 2017, doi: 10.1080/01431161.2016.1219425.</li>
<li>T. R. H. Goodbody, N. C. Coops, P. L. Marshall, P. Tompalski, and P. Crawford, “Unmanned aerial systems for precision forest inventory purposes: A review and case study,” For. Chron., vol. 93, no. 1, pp. 71–81, 2017, doi: 10.5558/tfc2017-012.</li>
<li>T. R. H. Goodbody, N. C. Coops, T. Hermosilla, P. Tompalski, G. McCartney, and D. A. MacLean, “Digital aerial photogrammetry for assessing cumulative spruce budworm defoliation and enhancing forest inventories at a landscape-level,” ISPRS J. Photogramm. Remote Sens., vol. 142, no. April, pp. 1–11, 2018, doi: 10.1016/j.isprsjprs.2018.05.012.</li>
<li>T. R. H. Goodbody, N. C. Coops, T. Hermosilla, P. Tompalski, and P. Crawford, “Assessing the status of forest regeneration using digital aerial photogrammetry and unmanned aerial systems,” Int. J. Remote Sens., vol. 39, no. 15–16, pp. 5246–5264, 2018, doi: 10.1080/01431161.2017.1402387.</li>
<li>T. R. H. Goodbody, N. C. Coops, T. Hermosilla, P. Tompalski, and G. Pelletier, “Vegetation phenology driving error variation in digital aerial photogrammetrically derived Terrain Models,” Remote Sens., vol. 10, no. 10, pp. 1–15, 2018, doi: 10.3390/rs10101554.</li>
<li>R. J. G. Nuijten, N. C. Coops, T. R. H. Goodbody, and G. Pelletier, “Examining the multi-seasonal consistency of individual tree segmentation on deciduous stands using Digital Aerial Photogrammetry (DAP) and unmanned aerial systems (UAS),” Remote Sens., vol. 11, no. 7, 2019, doi: 10.3390/rs11070739.</li>
<li>T. R. H. Goodbody, N. C. Coops, and J. C. White, “Digital Aerial Photogrammetry for Updating Area-Based Forest Inventories: A Review of Opportunities, Challenges, and Future Directions,” Curr. For. Reports, pp. 55–75, 2019, doi: 10.1007/s40725-019-00087-2.</li>
<li>N. C. Coops, T. R. H. Goodbody, and L. Cao, “Four steps to extend drone use in research,” Nature, pp. 7–9, 2019.</li>
<li>J. M. M. Yancho, N. C. Coops, P. Tompalski, T. R. H. Goodbody, and A. Plowright, “Fine-Scale Spatial and Spectral Clustering of UAV-Acquired Digital Aerial Photogrammetric (DAP) Point Clouds for Individual Tree Crown Detection and Segmentation,” IEEE J. Sel. Top. Appl. Earth Obs. Remote Sens., vol. 12, no. 10, pp. 4131–4148, 2019, doi: 10.1109/JSTARS.2019.2942811.</li>
<li>A. Graham, N. C. Coops, M. Wilcox, and A. Plowright, “Evaluation of ground surface models derived from unmanned aerial systems with digital aerial photogrammetry in a disturbed conifer forest,” Remote Sens., vol. 11, no. 1, 2019, doi: 10.3390/rs11010084.</li>
<li>A. N. V. Graham, N. C. Coops, P. Tompalski, A. Plowright, and M. Wilcox, “Effect of ground surface interpolation methods on the accuracy of forest attribute modelling using unmanned aerial systems-based digital aerial photogrammetry,” Int. J. Remote Sens., vol. 41, no. 9, pp. 3287–3306, 2020, doi: 10.1080/01431161.2019.1694722.</li>
<li>P. Tompalski, J. Rakofsky, N. C. Coops, J. C. White, A. N. V. Graham, and K. Rosychuk, “Challenges of multi-temporal and multi-sensor forest growth analyses in a highly disturbed boreal mixedwood forests,” Remote Sens., vol. 11, no. 18, 2019, doi: 10.3390/rs11182102.</li>
<li>A. J. Chadwick et al., “Automatic delineation and height measurement of regenerating conifer crowns under leaf-off conditions using uav imagery,” Remote Sens., vol. 12, no. 24, pp. 1–26, 2020, doi: 10.3390/rs12244104.</li>
<li>Z. Xu et al., “Tree species classification using UAS-based digital aerial photogrammetry point clouds and multispectral imageries in subtropical natural forests,” Int. J. Appl. Earth Obs. Geoinf., vol. 92, no. May, p. 102173, 2020, doi: 10.1016/j.jag.2020.102173.</li>
<li>J. R. Roussel et al., “lidR: An R package for analysis of Airborne Laser Scanning (ALS) data,” Remote Sens. Environ., vol. 251, no. September, p. 112061, 2020, doi: 10.1016/j.rse.2020.112061.</li>
<li>P. Tompalski et al., “Estimating Changes in Forest Attributes and Enhancing Growth Projections: a Review of Existing Approaches and Future Directions Using Airborne 3D Point Cloud Data (Current Forestry Reports, (2021), 7, 1, (1-24), 10.1007/s40725-021-00,” Curr. For. Reports, vol. 7, no. 1, pp. 25–30, 2021, doi: 10.1007/s40725-021-00139-6.</li>
<li>X. Fu et al., “Assessment of approaches for monitoring forest structure dynamics using bi-temporal digital aerial photogrammetry point clouds,” Remote Sens. Environ., vol. 255, no. January, p. 112300, 2021, doi: 10.1016/j.rse.2021.112300.</li>
<li>T. R. H. Goodbody, J. C. White, N. C. Coops, and A. LeBoeuf, “Benchmarking acquisition parameters for digital aerial photogrammetric data for forest inventory applications: Impacts of image overlap and resolution,” Remote Sens. Environ., vol. 265, no. August, p. 112677, 2021, doi: 10.1016/j.rse.2021.112677.</li>
<li>A. J. Chadwick, N. C. Coops, C. W. Bater, L. A. Martens, and B. White, “Species Classification of Automatically Delineated Regenerating Conifer Crowns Using RGB and Near-Infrared UAV Imagery,” IEEE Geosci. Remote Sens. Lett., vol. 19, 2022, doi: 10.1109/LGRS.2021.3123552.</li>
<li>J. Arkin, N. C. Coops, T. Hermosilla, L. D. Daniels, and A. Plowright, “Integrated fire severity-land cover mapping using very-high-spatial-resolution aerial imagery and point clouds,” Int. J. Wildl. Fire, vol. 28, no. 11, pp. 840–860, 2019, doi: 10.1071/WF19008.</li>
<li>R. J. G. Nuijten, N. C. Coops, C. Watson, and D. Theberge, “Monitoring the structure of regenerating vegetation using drone-based digital aerial photogrammetry,” Remote Sens., vol. 13, no. 10, 2021, doi: 10.3390/rs13101942.</li>
</ol>