# Introduction {#intro}
Remotely piloted aerial systems (RPAS) have emerged as remote sensing platforms capable of capturing imagery at finer spatial resolutions than conventional aerial and spaceborne platforms. Along with the proliferation of commercially available RPAS has come an emergence of digital aerial photogrammetry (DAP) techniques, which have enabled the derivation of three-dimensional (3D) point cloud data from overlapping imagery. Members of the University of British Columbia’s Integrated Remote Sensing Studio Integrated Remote Sensing Studio (IRSS) have undertaken investigations into a wide range of forestry solutions utilizing orthomosaics and photogrammetric point clouds derived from fine spatial resolution RPAS imagery, and have since developed an expert knowledgebase on the use of RPAS and DAP technologies.

In 2018, IRSS members began collaboration with partners at the Government of Alberta, with the ultimate goal of leveraging RPAS and DAP to deliver post-harvest inventory information in an accurate, consistent, and repeatable manner. We have since developed guidelines on how to best acquire and process RPAS-borne data to characterize regeneration 12-14 years post-harvest with DAP products. The following report is divided into three main sections. The report is a synthesis of knowledge and is presented as a best practices guide. While tailored towards regeneration approaches, the principles discussed in this report are likely to be useful for applications in other forest conditions. 
